version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: sonarqube-playground-postgres
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-network
  sonarqube:
    image: sonarqube:8.2-community
    container_name: sonarqube-playground-sonar
    ports:
      - '9000:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5433/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonar-network
    command: >
      sh -c "chown -R 0:0 /opt/sonarqube && chmod -R 770 /opt/sonarqube"
    depends_on:
      - postgres
networks:
    sonar-network:
      driver: bridge
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data: