version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: blibli-engagement-zookeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - blibli
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: blibli-engagement-kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://52.187.23.103:9092,EXTERNAL://52.187.23.103:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://52.187.23.103:9092,EXTERNAL://52.187.23.103:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on: 
      - zookeeper
    networks:
      - blibli
  mongodb:
    image: mongo:3.6
    container_name: blibli-engagement-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - blibli-engagement-mongodb:/data/db
    networks:
      - blibli
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ternakkode
      MONGO_INITDB_ROOT_PASSWORD: rahasia123
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: blibli-engagement-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - blibli-engagement-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - blibli
  redis:
    image: redis:latest
    container_name: blibli-engagement-redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=rahasia123
    command: redis-server --requirepass rahasia123
  postgres:
    image: postgres:latest
    container_name: blibli-engagement-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ternakkode
      - POSTGRES_PASSWORD=rahasia123
      - POSTGRES_DB=blibli-enngagement-dev
    volumes:
      - blibli-engagement-postgres:/var/lib/postgresql/data
networks:
    blibli:
      driver: bridge
volumes:
    blibli-engagement-mongodb:
      driver: local
    blibli-engagement-elasticsearch:
      driver: local
    blibli-engagement-postgres:
      driver: local