version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.4.12'
    container_name: blibli-engagement-zookeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
  kafka:
    image: 'bitnami/kafka:1.1.0'
    container_name: blibli-engagement-kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=52.187.23.103:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://52.187.23.103:9092,EXTERNAL://52.187.23.103:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on: 
      - zookeeper
  mongodb:
    image: mongo:3.6
    container_name: blibli-engagement-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - blibli-engagement-mongodb:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: blibli-engagement-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - blibli-engagement-elasticsearch:/usr/share/elasticsearch/data
  redis:
    image: redis:latest
    container_name: blibli-engagement-redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=rahasia123
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    container_name: blibli-engagement-redis-sentinel
    environment:
      - REDIS_MASTER_HOST=52.187.23.103
      - REDIS_MASTER_PASSWORD=rahasia123
    ports:
      - '26379:26379'
  postgres:
    image: postgres:latest
    container_name: blibli-engagement-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ternakkode
      - POSTGRES_PASSWORD=rahasia123
      - POSTGRES_DB=blibli-enngagement-dev
    volumes:
      - blibli-engagement-postgres:/var/lib/postgresql/data
volumes:
    blibli-engagement-mongodb:
      driver: local
    blibli-engagement-elasticsearch:
      driver: local
    blibli-engagement-postgres:
      driver: local